name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.0'

    - name: Install Rust (Nightly)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Install Clang/LLVM
      run: sudo apt-get update && sudo apt-get install -y clang cmake

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: moodiary-apk
        path: build/app/outputs/flutter-apk/app-release.apk